name: Djang0 Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# on:
#   schedule:
#     cron: "0 0 * * *"
#     node_name: "test-cron"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python requirements.txt
      uses: actions/setup-python@v2
      with:
        python-version: requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests flake8
      run: |
        pip install flake8
        flake8 .
    - name: Coberage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report -m